{% set name = "grpcio-reflection" %}
{% set version = "1.73.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 2d6a420264e31e83e81114dd2586b5cd05a6c689b01dd5e2121d91f2b4e167f2

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - grpcio ={{ version }}
    - protobuf >=3.12.0
    - python >={{ python_min }}

test:
  imports:
    - grpc_reflection
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://grpc.io
  summary: Standard Protobuf Reflection Service for gRPC
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - lidavidm
    - mariusvniekerk
