{% set name = "grpcio-reflection" %}
{% set version = "1.54.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/grpcio-reflection-{{ version }}.tar.gz
  sha256: b2e021e1ce4f075615411edfbbd6fdcc485ba474dd6e5a3f559690582959a673

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - grpcio ={{ version }}
    - protobuf >=3.12.0
    - python >=3.6

test:
  imports:
    - grpc_reflection
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://grpc.io
  summary: Standard Protobuf Reflection Service for gRPC
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - lidavidm
    - mariusvniekerk
