{% set name = "grpcio-reflection" %}
{% set version = "1.60.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/grpcio-reflection-{{ version }}.tar.gz
  sha256: 3f6c0c73ba8f20d1420c5e72fc4dd0389fac346ed8fb32a28e6e1967b44fff35

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - grpcio ={{ version }}
    - protobuf >=3.12.0
    - python >=3.6

test:
  imports:
    - grpc_reflection
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://grpc.io
  summary: Standard Protobuf Reflection Service for gRPC
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - lidavidm
    - mariusvniekerk
