{% set name = "grpcio-reflection" %}
{% set version = "1.70.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: af46ce13e57fd7602deaef5b1d1903f6644f8982cc00f62fa9fa5b928acf6a49

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - grpcio ={{ version }}
    - protobuf >=3.12.0
    - python >={{ python_min }}

test:
  imports:
    - grpc_reflection
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://grpc.io
  summary: Standard Protobuf Reflection Service for gRPC
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - lidavidm
    - mariusvniekerk
